# Análise inicial dos datasets

Esta etapa contém uma exploração inicial (EDA) dos ficheiros em `src/Datasets/`, com código reutilizável em `src/DataEngineering/`.

In [ ]:

# project_root = Path.cwd().resolve()
# src_root = project_root / "src"
# if str(src_root) not in sys.path:
#     sys.path.insert(0, str(src_root))

from src.DataEngineering.data_loader import DataLoader
from src.DataEngineering.data_explorer import DataExplorer

datasets_dir =  "./src/Datasets"

## Formulário de avaliação — Turma 1

### Carregamento do Dataset

In [2]:
# Carregando o dataset
data_loader = DataLoader(datasets_dir / "form_avaliacao_turma_1.xlsx")
dataset_turma1_avaliacao = data_loader.load_data()
print("Dataset carregado com sucesso!")

Dataset carregado com sucesso!

### Exploração dos Dados (EDA)

Este tópico contém análises básicas para entender as características iniciais dos dados.

In [3]:
# Análise inicial
data_explorer = DataExplorer()
data_explorer.analyze(dataset_turma1_avaliacao)

Primeiras linhas do dataset:

,Carimbo de data/hora,Você trabalha com desenvolvimento de software?,"Com que frequência utiliza programação Orientado a objetos e seus aspectos (por exemplo, herança, polimorfismo)?",Você já tinha utilizado padrões de projeto em algum projeto?,"Você já tinha ouvido falar dos princípios SOLID (Responsabilidade Única, Aberto-Fechado, etc.)?",Você achou a metodologia aplicada eficiente para o ensino de padrões de projeto?,As explicações teóricas e os exemplos foram suficientes para entender os padrões de projeto?,Como você avalia a complexidade da primeira atividade proposta?,O projeto prático ajudou no entendimento dos padrões de projeto?,Os princípios SOLID abordados na prática auxiliaram na criação de código mais reutilizável e flexível?,"Em uma escala de 1 a 5, como você avalia sua confiança em aplicar padrões de projeto após essa experiência?",Quais aspectos das atividades contribuíram mais para o seu aprendizado sobre padrões de projeto?,Que sugestões você daria para melhorar o ensino de padrões de projeto?,Observações gerais
0,2025-02-21 11:51:59.378,"Não, nunca",2 - Raramente,"Não, nunca","Não, nunca ouvi falar",4 (Eficiente),4 (Suficientes),2 (Moderadas),4 (Ajudaram bastante),4 (Bastante),3 (Moderadamente confiante),Acredito que o incentivo a parte prática fizer...,Acho buscar uma forma mais lúdica de ensinar a...,NaN
1,2025-02-21 11:58:59.418,"Não, nunca",2 - Raramente,"Não, nunca","Não, nunca ouvi falar",4 (Eficiente),4 (Suficientes),1 (Difíceis),4 (Ajudaram bastante),3 (Moderadamente),3 (Moderadamente confiante),Construção de diagramas de classes com ou sem ...,Mais comparações de códigos usando e n usando,NaN
2,2025-02-21 12:07:59.616,"Não, nunca",3 - Às vezes,"Não, nunca","Não, nunca ouvi falar",4 (Eficiente),3 (Moderadamente suficientes),2 (Moderadas),4 (Ajudaram bastante),4 (Bastante),2 (Pouco confiante),A parte prática e o momento antes da apresenta...,Acredito que além de mostrar alguns exemplos s...,Foi bem legal a gente pegar um código já pront...
3,2025-02-21 12:08:34.828,"Sim, atualmente",4 - Frequentemente,"Sim, ocasionalmente","Sim, mas não sabia em detalhes",4 (Eficiente),3 (Moderadamente suficientes),3 (Fáceis),4 (Ajudaram bastante),4 (Bastante),3 (Moderadamente confiante),"Eu sempre fui melhor em aprender na prática, e...",A aula explicando os padrões não foi tão efici...,NaN
4,2025-02-21 12:10:26.068,"Não, nunca",4 - Frequentemente,"Não, nunca","Não, nunca ouvi falar",4 (Eficiente),3 (Moderadamente suficientes),2 (Moderadas),3 (Ajudaram moderadamente),3 (Moderadamente),2 (Pouco confiante),Dinâmica em grupo,A disciplina em si já se trata de um conteúdo ...,Obrigado

Resumo estatístico do dataset:

             Carimbo de data/hora
count                          23
mean   2025-02-22 04:46:59.028087
min    2025-02-21 11:51:59.378000
25%    2025-02-21 12:57:08.659500
50%    2025-02-21 14:56:33.531000
75%    2025-02-22 07:56:11.617000
max    2025-02-24 18:41:51.359000

Informações sobre os tipos de dados:
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 14 columns):
 #   Column                                                                                                            Non-Null Count  Dtype
---  ------                                                                                                            --------------  -----
 0   Carimbo de data/hora                                                                                              23 non-null     datetime64[us]
 1   Você trabalha com desenvolvimento de software?                                                                    23 non-null     str
 2   Com que frequência utiliza programação Orientado a objetos e seus aspectos (por exemplo, herança, polimorfismo)?  23 non-null     str
 3   Você já tinha utilizado padrões de projeto em algum projeto?                                                      23 non-null     str
 4   Você já tinha ouvido falar dos princípios SOLID (Responsabilidade Única, Aberto-Fechado, etc.)?                   23 non-null     str
 5   Você achou a metodologia aplicada eficiente para o ensino de padrões de projeto?                                  23 non-null     str
 6   As explicações teóricas e os exemplos foram suficientes para entender os padrões de projeto?                      23 non-null     str
 7   Como você avalia a complexidade da primeira atividade proposta?                                                   23 non-null     str
 8   O projeto prático ajudou no entendimento dos padrões de projeto?                                                  23 non-null     str
 9   Os princípios SOLID abordados na prática auxiliaram na criação de código mais reutilizável e flexível?            23 non-null     str
 10  Em uma escala de 1 a 5, como você avalia sua confiança em aplicar padrões de projeto após essa experiência?       23 non-null     str
 11  Quais aspectos das atividades contribuíram mais para o seu aprendizado sobre padrões de projeto?                  23 non-null     str
 12  Que sugestões você daria para melhorar o ensino de padrões de projeto?                                            23 non-null     str
 13  Observações gerais                                                                                                9 non-null      str
dtypes: datetime64[us](1), str(13)
memory usage: 2.6 KB

## Formulário de avaliação — Turma 2

### Carregamento do Dataset

In [4]:
# Carregando o dataset
data_loader = DataLoader(datasets_dir / "form_avaliacao_turma_2.xlsx")
dataset_turma2_avaliacao = data_loader.load_data()
print("Dataset carregado com sucesso!")

Dataset carregado com sucesso!

### Exploração dos Dados (EDA)

Este tópico contém análises básicas para entender as características iniciais dos dados.

In [5]:
# Análise inicial
data_explorer = DataExplorer()
data_explorer.analyze(dataset_turma2_avaliacao)

Primeiras linhas do dataset:

,Carimbo de data/hora,Informe sua matrícula,Você achou a metodologia aplicada eficiente para o ensino de padrões de projeto?,As explicações teóricas e os exemplos foram suficientes para entender os padrões de projeto?,Como você avalia a complexidade da primeira atividade proposta?,Como você avalia a complexidade da segunda atividade proposta?,O projeto final (terceira atividade) ajudou no entendimento dos padrões de projeto?,Os padrões de projeto abordados na prática auxiliaram na criação de código mais reutilizável e flexível?,"Em uma escala de 1 a 4, como você avalia sua confiança em aplicar padrões de projeto após essa experiência?",Quais aspectos das atividades contribuíram mais para o seu aprendizado sobre padrões de projeto?,Que sugestões você daria para melhorar o ensino de padrões de projeto?,Observações gerais
0,2026-01-22 12:40:36.354,2023041652,4 (Eficiente),3 (Moderadamente suficientes),2 (Moderada),2 (Moderada),3 (Ajudou moderadamente),4 (Bastante),3 (Moderadamente confiante),"O uso direto dos padrões, pois isso força a co...",Mais exemplos práticos em aula com execução do...,NaN
1,2026-01-22 13:01:14.203,2022039702,4 (Eficiente),4 (Suficientes),2 (Moderada),3 (Fácil),4 (Ajudou bastante),4 (Bastante),3 (Moderadamente confiante),A parte pratica foi fundamental para o entendi...,Colocar mais praticas sobre esses padrões e at...,Ótima metodologia ficou muito claro o que foi ...
2,2026-01-22 14:08:18.087,2023034380,4 (Eficiente),3 (Moderadamente suficientes),2 (Moderada),3 (Fácil),4 (Ajudou bastante),4 (Bastante),3 (Moderadamente confiante),"o processo de refatorar códigos, pois ajuda a ...",explicar sobre programação orientada a objeto(...,NaN
3,2026-01-22 14:34:06.951,2023035726,3 (Moderadamente eficiente),3 (Moderadamente suficientes),3 (Fácil),2 (Moderada),4 (Ajudou bastante),4 (Bastante),3 (Moderadamente confiante),aplicação nas atividades propostas,utilizar exemplos mais claros e objetivos dura...,NaN
4,2026-01-22 17:00:35.600,2021042504,4 (Eficiente),4 (Suficientes),3 (Fácil),3 (Fácil),4 (Ajudou bastante),4 (Bastante),3 (Moderadamente confiante),Colocar em pratica o uso de padrões de projeto...,Acho que a aula de padrões deveria ser ministr...,NaN

Resumo estatístico do dataset:

             Carimbo de data/hora  Informe sua matrícula
count                          17           1.700000e+01
mean   2026-01-25 21:23:25.909588           5.235336e+09
min    2026-01-22 12:40:36.354000           2.021018e+09
25%    2026-01-22 17:00:35.600000           2.022024e+09
50%    2026-01-23 12:16:37.388000           2.022043e+09
75%    2026-01-23 13:57:47.921000           2.023042e+09
max    2026-02-16 19:21:49.468000           2.024006e+10
std                           NaN           7.154844e+09

Informações sobre os tipos de dados:
<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 12 columns):
 #   Column                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                       --------------  -----
 0   Carimbo de data/hora                                                                                         17 non-null     datetime64[us]
 1   Informe sua matrícula                                                                                        17 non-null     int64
 2   Você achou a metodologia aplicada eficiente para o ensino de padrões de projeto?                             17 non-null     str
 3   As explicações teóricas e os exemplos foram suficientes para entender os padrões de projeto?                 17 non-null     str
 4   Como você avalia a complexidade da primeira atividade proposta?                                              17 non-null     str
 5   Como você avalia a complexidade da segunda atividade proposta?                                               17 non-null     str
 6   O projeto final (terceira atividade) ajudou no entendimento dos padrões de projeto?                          17 non-null     str
 7   Os padrões de projeto abordados na prática auxiliaram na criação de código mais reutilizável e flexível?     17 non-null     str
 8   Em uma escala de 1 a 4, como você avalia sua confiança em aplicar padrões de projeto após essa experiência?  17 non-null     str
 9   Quais aspectos das atividades contribuíram mais para o seu aprendizado sobre padrões de projeto?             17 non-null     str
 10  Que sugestões você daria para melhorar o ensino de padrões de projeto?                                       17 non-null     str
 11  Observações gerais                                                                                           7 non-null      str
dtypes: datetime64[us](1), int64(1), str(10)
memory usage: 1.7 KB

## Formulário de caracterização — Turma 2

### Carregamento do Dataset

In [6]:
# Carregando o dataset
data_loader = DataLoader(datasets_dir / "form_caracterizacao_turma_2.xlsx")
dataset_turma2_caracterizacao = data_loader.load_data()
print("Dataset carregado com sucesso!")

Dataset carregado com sucesso!

### Exploração dos Dados (EDA)

Este tópico contém análises básicas para entender as características iniciais dos dados.

In [7]:
# Análise inicial
data_explorer = DataExplorer()
data_explorer.analyze(dataset_turma2_caracterizacao)

Primeiras linhas do dataset:

,Carimbo de data/hora,Informe sua matrícula,Você já trabalhou com desenvolvimento de software?,"Qual é o seu nível de conhecimento em programação orientada a objetos (POO), incluindo conceitos como herança e polimorfismo?",Você já tinha utilizado padrões de projeto em algum projeto?,"Você já tinha ouvido falar dos princípios SOLID (Responsabilidade Única, Aberto-Fechado, etc.)?",Quais linguagens de programação você já utilizou em seus projetos? (Selecione todas as que se aplicam),Quais ferramentas de desenvolvimento você utiliza ou já utilizou? (Selecione todas as que se aplicam)
0,2025-11-25 19:01:01.283,2021023397,"Não, nunca",3 - Conhecimento intermediário,"Não, nunca utilizei","Não, nunca ouvi falar","Python, Java, JavaScript, C, Lisp","Visual Studio Code, IntelliJ IDEA, PyCharm, Git"
1,2025-11-25 19:43:32.621,2023041652,"Não, nunca",2 - Conhecimento básico,"Não, nunca utilizei","Não, nunca ouvi falar","Python, Java","Visual Studio Code, Eclipse, PyCharm"
2,2025-11-25 20:43:08.743,2021042504,"Sim, mas apenas de forma acadêmica",2 - Conhecimento básico,"Não, nunca utilizei","Não, nunca ouvi falar","Python, JavaScript, C++, SQL, CSS","Visual Studio Code, Git, NetLogo"
3,2025-11-26 22:46:01.287,2022039702,"Sim, mas apenas de forma acadêmica",2 - Conhecimento básico,"Sim, apenas em estudos ou exemplos simples","Não, nunca ouvi falar","Python, JavaScript, C#","Visual Studio Code, IntelliJ IDEA, PyCharm, Git"
4,2025-11-26 23:03:28.863,20240044446,"Não, nunca",2 - Conhecimento básico,"Não, nunca utilizei","Já ouvi falar, mas não sei explicar",Python,"Visual Studio Code, PyCharm"

Resumo estatístico do dataset:

             Carimbo de data/hora  Informe sua matrícula
count                          28           2.800000e+01
mean   2025-11-27 06:27:20.928000           4.487653e+09
min    2025-11-25 19:01:01.283000           2.022000e+03
25%    2025-11-27 09:26:47.829000           2.022022e+09
50%    2025-11-27 11:21:51.562500           2.023035e+09
75%    2025-11-27 12:32:16.070250           2.023061e+09
max    2025-11-27 18:43:12.755000           2.024006e+10
std                           NaN           6.568066e+09

Informações sobre os tipos de dados:
<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 8 columns):
 #   Column                                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                                         --------------  -----
 0   Carimbo de data/hora                                                                                                           28 non-null     datetime64[us]
 1   Informe sua matrícula                                                                                                          28 non-null     int64
 2   Você já trabalhou com desenvolvimento de software?                                                                             28 non-null     str
 3   Qual é o seu nível de conhecimento em programação orientada a objetos (POO), incluindo conceitos como herança e polimorfismo?  28 non-null     str
 4   Você já tinha utilizado padrões de projeto em algum projeto?                                                                   28 non-null     str
 5   Você já tinha ouvido falar dos princípios SOLID (Responsabilidade Única, Aberto-Fechado, etc.)?                                28 non-null     str
 6   Quais linguagens de programação você já utilizou em seus projetos? (Selecione todas as que se aplicam)                         28 non-null     str
 7   Quais ferramentas de desenvolvimento você utiliza ou já utilizou? (Selecione todas as que se aplicam)                          28 non-null     str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 1.9 KB